-- Auto-generated by convert.py
return {
  name = "videoplayback",
  has_audio = "true",
  has_video = "true",
  fps = 5,
  frame_count = 1299,
  width = 153,
  height = 38,
  monitors_x = 3,
  monitors_y = 2,
  duration = 259.76,
}
