-- Auto-generated by convert.py
return {
  name = "aaaaa",
  has_audio = "true",
  has_video = "true",
  fps = 5,
  frame_count = 805,
  width = 408,
  height = 114,
  monitors_x = 8,
  monitors_y = 6,
  frame_ext = "nfph",
  duration = 161.08,
}
