-- Auto-generated by convert.py
return {
  name = "aaaaa",
  has_audio = "true",
  has_video = "true",
  fps = 5,
  frame_count = 805,
  width = 153,
  height = 38,
  monitors_x = 3,
  monitors_y = 2,
  frame_ext = "nfpc",
  duration = 161.08,
}
